// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: timeline/timeline.proto

package timeline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimelineService_GetFollowingFeed_FullMethodName = "/timeline.TimelineService/GetFollowingFeed"
	TimelineService_GetRecommendFeed_FullMethodName = "/timeline.TimelineService/GetRecommendFeed"
	TimelineService_GetUserFeed_FullMethodName      = "/timeline.TimelineService/GetUserFeed"
	TimelineService_GetHotFeed_FullMethodName       = "/timeline.TimelineService/GetHotFeed"
	TimelineService_GetContentDetail_FullMethodName = "/timeline.TimelineService/GetContentDetail"
)

// TimelineServiceClient is the client API for TimelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TimelineService 时间线服务
// 提供 Feed 流聚合功能
type TimelineServiceClient interface {
	// 获取关注用户的 Feed
	GetFollowingFeed(ctx context.Context, in *GetFollowingFeedRequest, opts ...grpc.CallOption) (*GetFollowingFeedResponse, error)
	// 获取推荐 Feed（预留）
	GetRecommendFeed(ctx context.Context, in *GetRecommendFeedRequest, opts ...grpc.CallOption) (*GetRecommendFeedResponse, error)
	// 获取指定用户的 Feed（用户主页）
	GetUserFeed(ctx context.Context, in *GetUserFeedRequest, opts ...grpc.CallOption) (*GetUserFeedResponse, error)
	// 获取热门 Feed
	GetHotFeed(ctx context.Context, in *GetHotFeedRequest, opts ...grpc.CallOption) (*GetHotFeedResponse, error)
	// 获取内容详情（包含交互状态）
	GetContentDetail(ctx context.Context, in *GetContentDetailRequest, opts ...grpc.CallOption) (*GetContentDetailResponse, error)
}

type timelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimelineServiceClient(cc grpc.ClientConnInterface) TimelineServiceClient {
	return &timelineServiceClient{cc}
}

func (c *timelineServiceClient) GetFollowingFeed(ctx context.Context, in *GetFollowingFeedRequest, opts ...grpc.CallOption) (*GetFollowingFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingFeedResponse)
	err := c.cc.Invoke(ctx, TimelineService_GetFollowingFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetRecommendFeed(ctx context.Context, in *GetRecommendFeedRequest, opts ...grpc.CallOption) (*GetRecommendFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendFeedResponse)
	err := c.cc.Invoke(ctx, TimelineService_GetRecommendFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetUserFeed(ctx context.Context, in *GetUserFeedRequest, opts ...grpc.CallOption) (*GetUserFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserFeedResponse)
	err := c.cc.Invoke(ctx, TimelineService_GetUserFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetHotFeed(ctx context.Context, in *GetHotFeedRequest, opts ...grpc.CallOption) (*GetHotFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotFeedResponse)
	err := c.cc.Invoke(ctx, TimelineService_GetHotFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetContentDetail(ctx context.Context, in *GetContentDetailRequest, opts ...grpc.CallOption) (*GetContentDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentDetailResponse)
	err := c.cc.Invoke(ctx, TimelineService_GetContentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimelineServiceServer is the server API for TimelineService service.
// All implementations must embed UnimplementedTimelineServiceServer
// for forward compatibility.
//
// TimelineService 时间线服务
// 提供 Feed 流聚合功能
type TimelineServiceServer interface {
	// 获取关注用户的 Feed
	GetFollowingFeed(context.Context, *GetFollowingFeedRequest) (*GetFollowingFeedResponse, error)
	// 获取推荐 Feed（预留）
	GetRecommendFeed(context.Context, *GetRecommendFeedRequest) (*GetRecommendFeedResponse, error)
	// 获取指定用户的 Feed（用户主页）
	GetUserFeed(context.Context, *GetUserFeedRequest) (*GetUserFeedResponse, error)
	// 获取热门 Feed
	GetHotFeed(context.Context, *GetHotFeedRequest) (*GetHotFeedResponse, error)
	// 获取内容详情（包含交互状态）
	GetContentDetail(context.Context, *GetContentDetailRequest) (*GetContentDetailResponse, error)
	mustEmbedUnimplementedTimelineServiceServer()
}

// UnimplementedTimelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimelineServiceServer struct{}

func (UnimplementedTimelineServiceServer) GetFollowingFeed(context.Context, *GetFollowingFeedRequest) (*GetFollowingFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowingFeed not implemented")
}
func (UnimplementedTimelineServiceServer) GetRecommendFeed(context.Context, *GetRecommendFeedRequest) (*GetRecommendFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendFeed not implemented")
}
func (UnimplementedTimelineServiceServer) GetUserFeed(context.Context, *GetUserFeedRequest) (*GetUserFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserFeed not implemented")
}
func (UnimplementedTimelineServiceServer) GetHotFeed(context.Context, *GetHotFeedRequest) (*GetHotFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotFeed not implemented")
}
func (UnimplementedTimelineServiceServer) GetContentDetail(context.Context, *GetContentDetailRequest) (*GetContentDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentDetail not implemented")
}
func (UnimplementedTimelineServiceServer) mustEmbedUnimplementedTimelineServiceServer() {}
func (UnimplementedTimelineServiceServer) testEmbeddedByValue()                         {}

// UnsafeTimelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimelineServiceServer will
// result in compilation errors.
type UnsafeTimelineServiceServer interface {
	mustEmbedUnimplementedTimelineServiceServer()
}

func RegisterTimelineServiceServer(s grpc.ServiceRegistrar, srv TimelineServiceServer) {
	// If the following call panics, it indicates UnimplementedTimelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimelineService_ServiceDesc, srv)
}

func _TimelineService_GetFollowingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetFollowingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_GetFollowingFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetFollowingFeed(ctx, req.(*GetFollowingFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetRecommendFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetRecommendFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_GetRecommendFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetRecommendFeed(ctx, req.(*GetRecommendFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetUserFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetUserFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_GetUserFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetUserFeed(ctx, req.(*GetUserFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetHotFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetHotFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_GetHotFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetHotFeed(ctx, req.(*GetHotFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetContentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetContentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_GetContentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetContentDetail(ctx, req.(*GetContentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimelineService_ServiceDesc is the grpc.ServiceDesc for TimelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timeline.TimelineService",
	HandlerType: (*TimelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowingFeed",
			Handler:    _TimelineService_GetFollowingFeed_Handler,
		},
		{
			MethodName: "GetRecommendFeed",
			Handler:    _TimelineService_GetRecommendFeed_Handler,
		},
		{
			MethodName: "GetUserFeed",
			Handler:    _TimelineService_GetUserFeed_Handler,
		},
		{
			MethodName: "GetHotFeed",
			Handler:    _TimelineService_GetHotFeed_Handler,
		},
		{
			MethodName: "GetContentDetail",
			Handler:    _TimelineService_GetContentDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeline/timeline.proto",
}
