// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: search/search.proto

package search

import (
	common "github.com/lesser/pkg/proto/common"
	post "github.com/lesser/post/proto/post"
	user "github.com/lesser/user/proto/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchPostsRequest 搜索帖子请求
type SearchPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PostType      post.PostType          `protobuf:"varint,2,opt,name=post_type,json=postType,proto3,enum=post.PostType" json:"post_type,omitempty"` // 可选，按类型筛选
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsRequest) Reset() {
	*x = SearchPostsRequest{}
	mi := &file_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsRequest) ProtoMessage() {}

func (x *SearchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsRequest.ProtoReflect.Descriptor instead.
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPostsRequest) GetPostType() post.PostType {
	if x != nil {
		return x.PostType
	}
	return post.PostType(0)
}

func (x *SearchPostsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SearchPostsResponse 搜索帖子响应
type SearchPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*post.Post           `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsResponse) Reset() {
	*x = SearchPostsResponse{}
	mi := &file_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsResponse) ProtoMessage() {}

func (x *SearchPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsResponse.ProtoReflect.Descriptor instead.
func (*SearchPostsResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPostsResponse) GetPosts() []*post.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchPostsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SearchUsersRequest 搜索用户请求
type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SearchUsersResponse 搜索用户响应
type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*user.Profile        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUsersResponse) GetUsers() []*user.Profile {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_search_search_proto protoreflect.FileDescriptor

const file_search_search_proto_rawDesc = "" +
	"\n" +
	"\x13search/search.proto\x12\x06search\x1a\x13common/common.proto\x1a\x0fpost/post.proto\x1a\x0fuser/user.proto\"\x8b\x01\n" +
	"\x12SearchPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12+\n" +
	"\tpost_type\x18\x02 \x01(\x0e2\x0e.post.PostTypeR\bpostType\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"k\n" +
	"\x13SearchPostsResponse\x12 \n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".post.PostR\x05posts\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"^\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"n\n" +
	"\x13SearchUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.user.ProfileR\x05users\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination2\x9f\x01\n" +
	"\rSearchService\x12F\n" +
	"\vSearchPosts\x12\x1a.search.SearchPostsRequest\x1a\x1b.search.SearchPostsResponse\x12F\n" +
	"\vSearchUsers\x12\x1a.search.SearchUsersRequest\x1a\x1b.search.SearchUsersResponseB'Z%github.com/lesser/search/proto/searchb\x06proto3"

var (
	file_search_search_proto_rawDescOnce sync.Once
	file_search_search_proto_rawDescData []byte
)

func file_search_search_proto_rawDescGZIP() []byte {
	file_search_search_proto_rawDescOnce.Do(func() {
		file_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)))
	})
	return file_search_search_proto_rawDescData
}

var file_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_search_search_proto_goTypes = []any{
	(*SearchPostsRequest)(nil),  // 0: search.SearchPostsRequest
	(*SearchPostsResponse)(nil), // 1: search.SearchPostsResponse
	(*SearchUsersRequest)(nil),  // 2: search.SearchUsersRequest
	(*SearchUsersResponse)(nil), // 3: search.SearchUsersResponse
	(post.PostType)(0),          // 4: post.PostType
	(*common.Pagination)(nil),   // 5: common.Pagination
	(*post.Post)(nil),           // 6: post.Post
	(*user.Profile)(nil),        // 7: user.Profile
}
var file_search_search_proto_depIdxs = []int32{
	4, // 0: search.SearchPostsRequest.post_type:type_name -> post.PostType
	5, // 1: search.SearchPostsRequest.pagination:type_name -> common.Pagination
	6, // 2: search.SearchPostsResponse.posts:type_name -> post.Post
	5, // 3: search.SearchPostsResponse.pagination:type_name -> common.Pagination
	5, // 4: search.SearchUsersRequest.pagination:type_name -> common.Pagination
	7, // 5: search.SearchUsersResponse.users:type_name -> user.Profile
	5, // 6: search.SearchUsersResponse.pagination:type_name -> common.Pagination
	0, // 7: search.SearchService.SearchPosts:input_type -> search.SearchPostsRequest
	2, // 8: search.SearchService.SearchUsers:input_type -> search.SearchUsersRequest
	1, // 9: search.SearchService.SearchPosts:output_type -> search.SearchPostsResponse
	3, // 10: search.SearchService.SearchUsers:output_type -> search.SearchUsersResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_search_search_proto_init() }
func file_search_search_proto_init() {
	if File_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_search_proto_goTypes,
		DependencyIndexes: file_search_search_proto_depIdxs,
		MessageInfos:      file_search_search_proto_msgTypes,
	}.Build()
	File_search_search_proto = out.File
	file_search_search_proto_goTypes = nil
	file_search_search_proto_depIdxs = nil
}
