// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: channel/channel.proto

package channel

import (
	common "github.com/funcdfs/lesser/pkg/gen_protos/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	OwnerId         string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AdminIds        []string               `protobuf:"bytes,6,rep,name=admin_ids,json=adminIds,proto3" json:"admin_ids,omitempty"`
	SubscriberCount int64                  `protobuf:"varint,7,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	PostCount       int64                  `protobuf:"varint,8,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	CreatedAt       *common.Timestamp      `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *common.Timestamp      `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsSubscribed    bool                   `protobuf:"varint,11,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,12,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsOwner         bool                   `protobuf:"varint,13,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	PinnedPost      *ChannelPost           `protobuf:"bytes,14,opt,name=pinned_post,json=pinnedPost,proto3" json:"pinned_post,omitempty"`
	Username        string                 `protobuf:"bytes,15,opt,name=username,proto3" json:"username,omitempty"`
	IsPublic        bool                   `protobuf:"varint,16,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_channel_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Channel) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Channel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Channel) GetAdminIds() []string {
	if x != nil {
		return x.AdminIds
	}
	return nil
}

func (x *Channel) GetSubscriberCount() int64 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *Channel) GetPostCount() int64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *Channel) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Channel) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Channel) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *Channel) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Channel) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *Channel) GetPinnedPost() *ChannelPost {
	if x != nil {
		return x.PinnedPost
	}
	return nil
}

func (x *Channel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Channel) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type ChannelPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,5,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	ViewCount     int64                  `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *common.Timestamp      `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsPinned      bool                   `protobuf:"varint,9,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	IsEdited      bool                   `protobuf:"varint,10,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`
	AuthorName    string                 `protobuf:"bytes,11,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelPost) Reset() {
	*x = ChannelPost{}
	mi := &file_channel_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPost) ProtoMessage() {}

func (x *ChannelPost) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPost.ProtoReflect.Descriptor instead.
func (*ChannelPost) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelPost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelPost) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelPost) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ChannelPost) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChannelPost) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *ChannelPost) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ChannelPost) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChannelPost) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ChannelPost) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *ChannelPost) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *ChannelPost) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type Subscriber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	SubscribedAt  *common.Timestamp      `protobuf:"bytes,4,opt,name=subscribed_at,json=subscribedAt,proto3" json:"subscribed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscriber) Reset() {
	*x = Subscriber{}
	mi := &file_channel_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscriber) ProtoMessage() {}

func (x *Subscriber) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscriber.ProtoReflect.Descriptor instead.
func (*Subscriber) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{2}
}

func (x *Subscriber) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscriber) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Subscriber) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Subscriber) GetSubscribedAt() *common.Timestamp {
	if x != nil {
		return x.SubscribedAt
	}
	return nil
}

type Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsOwner       bool                   `protobuf:"varint,4,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	AddedAt       *common.Timestamp      `protobuf:"bytes,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_channel_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{3}
}

func (x *Admin) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Admin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Admin) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Admin) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *Admin) GetAddedAt() *common.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_channel_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateChannelRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CreateChannelRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateChannelRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_channel_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{5}
}

func (x *GetChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type UpdateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	IsPublic      bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	mi := &file_channel_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UpdateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChannelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateChannelRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateChannelRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateChannelRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_channel_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetSubscribedChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribedChannelsRequest) Reset() {
	*x = GetSubscribedChannelsRequest{}
	mi := &file_channel_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribedChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribedChannelsRequest) ProtoMessage() {}

func (x *GetSubscribedChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribedChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribedChannelsRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubscribedChannelsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSubscribedChannelsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetOwnedChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnedChannelsRequest) Reset() {
	*x = GetOwnedChannelsRequest{}
	mi := &file_channel_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnedChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnedChannelsRequest) ProtoMessage() {}

func (x *GetOwnedChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnedChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetOwnedChannelsRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{9}
}

func (x *GetOwnedChannelsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOwnedChannelsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChannelsRequest) Reset() {
	*x = SearchChannelsRequest{}
	mi := &file_channel_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChannelsRequest) ProtoMessage() {}

func (x *SearchChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChannelsRequest.ProtoReflect.Descriptor instead.
func (*SearchChannelsRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{10}
}

func (x *SearchChannelsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchChannelsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelsResponse) Reset() {
	*x = ChannelsResponse{}
	mi := &file_channel_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelsResponse) ProtoMessage() {}

func (x *ChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelsResponse.ProtoReflect.Descriptor instead.
func (*ChannelsResponse) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ChannelsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_channel_channel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_channel_channel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{13}
}

func (x *UnsubscribeRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetSubscribersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribersRequest) Reset() {
	*x = GetSubscribersRequest{}
	mi := &file_channel_channel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribersRequest) ProtoMessage() {}

func (x *GetSubscribersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribersRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribersRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{14}
}

func (x *GetSubscribersRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetSubscribersRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SubscribersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribers   []*Subscriber          `protobuf:"bytes,1,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribersResponse) Reset() {
	*x = SubscribersResponse{}
	mi := &file_channel_channel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribersResponse) ProtoMessage() {}

func (x *SubscribersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribersResponse.ProtoReflect.Descriptor instead.
func (*SubscribersResponse) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribersResponse) GetSubscribers() []*Subscriber {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

func (x *SubscribersResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CheckSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSubscriptionRequest) Reset() {
	*x = CheckSubscriptionRequest{}
	mi := &file_channel_channel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubscriptionRequest) ProtoMessage() {}

func (x *CheckSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CheckSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{16}
}

func (x *CheckSubscriptionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type CheckSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSubscribed  bool                   `protobuf:"varint,1,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSubscriptionResponse) Reset() {
	*x = CheckSubscriptionResponse{}
	mi := &file_channel_channel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubscriptionResponse) ProtoMessage() {}

func (x *CheckSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CheckSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{17}
}

func (x *CheckSubscriptionResponse) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

type AddAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminRequest) Reset() {
	*x = AddAdminRequest{}
	mi := &file_channel_channel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminRequest) ProtoMessage() {}

func (x *AddAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminRequest.ProtoReflect.Descriptor instead.
func (*AddAdminRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{18}
}

func (x *AddAdminRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *AddAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminRequest) Reset() {
	*x = RemoveAdminRequest{}
	mi := &file_channel_channel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminRequest) ProtoMessage() {}

func (x *RemoveAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminRequest.ProtoReflect.Descriptor instead.
func (*RemoveAdminRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveAdminRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *RemoveAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAdminsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminsRequest) Reset() {
	*x = GetAdminsRequest{}
	mi := &file_channel_channel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminsRequest) ProtoMessage() {}

func (x *GetAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminsRequest.ProtoReflect.Descriptor instead.
func (*GetAdminsRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{20}
}

func (x *GetAdminsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type AdminsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*Admin               `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminsResponse) Reset() {
	*x = AdminsResponse{}
	mi := &file_channel_channel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminsResponse) ProtoMessage() {}

func (x *AdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminsResponse.ProtoReflect.Descriptor instead.
func (*AdminsResponse) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{21}
}

func (x *AdminsResponse) GetAdmins() []*Admin {
	if x != nil {
		return x.Admins
	}
	return nil
}

type PublishPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishPostRequest) Reset() {
	*x = PublishPostRequest{}
	mi := &file_channel_channel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostRequest) ProtoMessage() {}

func (x *PublishPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostRequest.ProtoReflect.Descriptor instead.
func (*PublishPostRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{22}
}

func (x *PublishPostRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PublishPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishPostRequest) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_channel_channel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{23}
}

func (x *GetPostsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetPostsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_channel_channel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{24}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type EditPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostRequest) Reset() {
	*x = EditPostRequest{}
	mi := &file_channel_channel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostRequest) ProtoMessage() {}

func (x *EditPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostRequest.ProtoReflect.Descriptor instead.
func (*EditPostRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{25}
}

func (x *EditPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *EditPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditPostRequest) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_channel_channel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{26}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PinPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPostRequest) Reset() {
	*x = PinPostRequest{}
	mi := &file_channel_channel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPostRequest) ProtoMessage() {}

func (x *PinPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPostRequest.ProtoReflect.Descriptor instead.
func (*PinPostRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{27}
}

func (x *PinPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type UnpinPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinPostRequest) Reset() {
	*x = UnpinPostRequest{}
	mi := &file_channel_channel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinPostRequest) ProtoMessage() {}

func (x *UnpinPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinPostRequest.ProtoReflect.Descriptor instead.
func (*UnpinPostRequest) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{28}
}

func (x *UnpinPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*ChannelPost         `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostsResponse) Reset() {
	*x = PostsResponse{}
	mi := &file_channel_channel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsResponse) ProtoMessage() {}

func (x *PostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsResponse.ProtoReflect.Descriptor instead.
func (*PostsResponse) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{29}
}

func (x *PostsResponse) GetPosts() []*ChannelPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *PostsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ChannelClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChannelClientEvent_Subscribe
	//	*ChannelClientEvent_Unsubscribe
	//	*ChannelClientEvent_Ping
	Event         isChannelClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelClientEvent) Reset() {
	*x = ChannelClientEvent{}
	mi := &file_channel_channel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelClientEvent) ProtoMessage() {}

func (x *ChannelClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelClientEvent.ProtoReflect.Descriptor instead.
func (*ChannelClientEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{30}
}

func (x *ChannelClientEvent) GetEvent() isChannelClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChannelClientEvent) GetSubscribe() *ChannelSubscribeEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelClientEvent_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ChannelClientEvent) GetUnsubscribe() *ChannelUnsubscribeEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelClientEvent_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ChannelClientEvent) GetPing() *ChannelPingEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelClientEvent_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isChannelClientEvent_Event interface {
	isChannelClientEvent_Event()
}

type ChannelClientEvent_Subscribe struct {
	Subscribe *ChannelSubscribeEvent `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type ChannelClientEvent_Unsubscribe struct {
	Unsubscribe *ChannelUnsubscribeEvent `protobuf:"bytes,2,opt,name=unsubscribe,proto3,oneof"`
}

type ChannelClientEvent_Ping struct {
	Ping *ChannelPingEvent `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ChannelClientEvent_Subscribe) isChannelClientEvent_Event() {}

func (*ChannelClientEvent_Unsubscribe) isChannelClientEvent_Event() {}

func (*ChannelClientEvent_Ping) isChannelClientEvent_Event() {}

type ChannelSubscribeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSubscribeEvent) Reset() {
	*x = ChannelSubscribeEvent{}
	mi := &file_channel_channel_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSubscribeEvent) ProtoMessage() {}

func (x *ChannelSubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSubscribeEvent.ProtoReflect.Descriptor instead.
func (*ChannelSubscribeEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{31}
}

func (x *ChannelSubscribeEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelUnsubscribeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUnsubscribeEvent) Reset() {
	*x = ChannelUnsubscribeEvent{}
	mi := &file_channel_channel_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUnsubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUnsubscribeEvent) ProtoMessage() {}

func (x *ChannelUnsubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUnsubscribeEvent.ProtoReflect.Descriptor instead.
func (*ChannelUnsubscribeEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{32}
}

func (x *ChannelUnsubscribeEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelPingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelPingEvent) Reset() {
	*x = ChannelPingEvent{}
	mi := &file_channel_channel_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPingEvent) ProtoMessage() {}

func (x *ChannelPingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPingEvent.ProtoReflect.Descriptor instead.
func (*ChannelPingEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{33}
}

type ChannelServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChannelServerEvent_NewPost
	//	*ChannelServerEvent_PostEdited
	//	*ChannelServerEvent_PostDeleted
	//	*ChannelServerEvent_PostPinned
	//	*ChannelServerEvent_PostUnpinned
	//	*ChannelServerEvent_ChannelUpdated
	//	*ChannelServerEvent_ChannelDeleted
	//	*ChannelServerEvent_Subscribed
	//	*ChannelServerEvent_Unsubscribed
	//	*ChannelServerEvent_Pong
	//	*ChannelServerEvent_Error
	Event         isChannelServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelServerEvent) Reset() {
	*x = ChannelServerEvent{}
	mi := &file_channel_channel_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelServerEvent) ProtoMessage() {}

func (x *ChannelServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelServerEvent.ProtoReflect.Descriptor instead.
func (*ChannelServerEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{34}
}

func (x *ChannelServerEvent) GetEvent() isChannelServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChannelServerEvent) GetNewPost() *NewPostEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_NewPost); ok {
			return x.NewPost
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetPostEdited() *PostEditedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_PostEdited); ok {
			return x.PostEdited
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetPostDeleted() *PostDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_PostDeleted); ok {
			return x.PostDeleted
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetPostPinned() *PostPinnedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_PostPinned); ok {
			return x.PostPinned
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetPostUnpinned() *PostUnpinnedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_PostUnpinned); ok {
			return x.PostUnpinned
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetChannelUpdated() *ChannelUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_ChannelUpdated); ok {
			return x.ChannelUpdated
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetChannelDeleted() *ChannelDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_ChannelDeleted); ok {
			return x.ChannelDeleted
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetSubscribed() *ChannelSubscribedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_Subscribed); ok {
			return x.Subscribed
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetUnsubscribed() *ChannelUnsubscribedEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_Unsubscribed); ok {
			return x.Unsubscribed
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetPong() *ChannelPongEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ChannelServerEvent) GetError() *ChannelErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ChannelServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChannelServerEvent_Event interface {
	isChannelServerEvent_Event()
}

type ChannelServerEvent_NewPost struct {
	NewPost *NewPostEvent `protobuf:"bytes,1,opt,name=new_post,json=newPost,proto3,oneof"`
}

type ChannelServerEvent_PostEdited struct {
	PostEdited *PostEditedEvent `protobuf:"bytes,2,opt,name=post_edited,json=postEdited,proto3,oneof"`
}

type ChannelServerEvent_PostDeleted struct {
	PostDeleted *PostDeletedEvent `protobuf:"bytes,3,opt,name=post_deleted,json=postDeleted,proto3,oneof"`
}

type ChannelServerEvent_PostPinned struct {
	PostPinned *PostPinnedEvent `protobuf:"bytes,4,opt,name=post_pinned,json=postPinned,proto3,oneof"`
}

type ChannelServerEvent_PostUnpinned struct {
	PostUnpinned *PostUnpinnedEvent `protobuf:"bytes,5,opt,name=post_unpinned,json=postUnpinned,proto3,oneof"`
}

type ChannelServerEvent_ChannelUpdated struct {
	ChannelUpdated *ChannelUpdatedEvent `protobuf:"bytes,6,opt,name=channel_updated,json=channelUpdated,proto3,oneof"`
}

type ChannelServerEvent_ChannelDeleted struct {
	ChannelDeleted *ChannelDeletedEvent `protobuf:"bytes,7,opt,name=channel_deleted,json=channelDeleted,proto3,oneof"`
}

type ChannelServerEvent_Subscribed struct {
	Subscribed *ChannelSubscribedEvent `protobuf:"bytes,8,opt,name=subscribed,proto3,oneof"`
}

type ChannelServerEvent_Unsubscribed struct {
	Unsubscribed *ChannelUnsubscribedEvent `protobuf:"bytes,9,opt,name=unsubscribed,proto3,oneof"`
}

type ChannelServerEvent_Pong struct {
	Pong *ChannelPongEvent `protobuf:"bytes,10,opt,name=pong,proto3,oneof"`
}

type ChannelServerEvent_Error struct {
	Error *ChannelErrorEvent `protobuf:"bytes,11,opt,name=error,proto3,oneof"`
}

func (*ChannelServerEvent_NewPost) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_PostEdited) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_PostDeleted) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_PostPinned) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_PostUnpinned) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_ChannelUpdated) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_ChannelDeleted) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_Subscribed) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_Unsubscribed) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_Pong) isChannelServerEvent_Event() {}

func (*ChannelServerEvent_Error) isChannelServerEvent_Event() {}

type NewPostEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *ChannelPost           `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPostEvent) Reset() {
	*x = NewPostEvent{}
	mi := &file_channel_channel_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPostEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPostEvent) ProtoMessage() {}

func (x *NewPostEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPostEvent.ProtoReflect.Descriptor instead.
func (*NewPostEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{35}
}

func (x *NewPostEvent) GetPost() *ChannelPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostEditedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *ChannelPost           `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostEditedEvent) Reset() {
	*x = PostEditedEvent{}
	mi := &file_channel_channel_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostEditedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEditedEvent) ProtoMessage() {}

func (x *PostEditedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEditedEvent.ProtoReflect.Descriptor instead.
func (*PostEditedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{36}
}

func (x *PostEditedEvent) GetPost() *ChannelPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDeletedEvent) Reset() {
	*x = PostDeletedEvent{}
	mi := &file_channel_channel_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeletedEvent) ProtoMessage() {}

func (x *PostDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeletedEvent.ProtoReflect.Descriptor instead.
func (*PostDeletedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{37}
}

func (x *PostDeletedEvent) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostDeletedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type PostPinnedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *ChannelPost           `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPinnedEvent) Reset() {
	*x = PostPinnedEvent{}
	mi := &file_channel_channel_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPinnedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPinnedEvent) ProtoMessage() {}

func (x *PostPinnedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPinnedEvent.ProtoReflect.Descriptor instead.
func (*PostPinnedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{38}
}

func (x *PostPinnedEvent) GetPost() *ChannelPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostUnpinnedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUnpinnedEvent) Reset() {
	*x = PostUnpinnedEvent{}
	mi := &file_channel_channel_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUnpinnedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUnpinnedEvent) ProtoMessage() {}

func (x *PostUnpinnedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUnpinnedEvent.ProtoReflect.Descriptor instead.
func (*PostUnpinnedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{39}
}

func (x *PostUnpinnedEvent) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostUnpinnedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUpdatedEvent) Reset() {
	*x = ChannelUpdatedEvent{}
	mi := &file_channel_channel_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdatedEvent) ProtoMessage() {}

func (x *ChannelUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ChannelUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{40}
}

func (x *ChannelUpdatedEvent) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ChannelDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelDeletedEvent) Reset() {
	*x = ChannelDeletedEvent{}
	mi := &file_channel_channel_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelDeletedEvent) ProtoMessage() {}

func (x *ChannelDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelDeletedEvent.ProtoReflect.Descriptor instead.
func (*ChannelDeletedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{41}
}

func (x *ChannelDeletedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelSubscribedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSubscribedEvent) Reset() {
	*x = ChannelSubscribedEvent{}
	mi := &file_channel_channel_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSubscribedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSubscribedEvent) ProtoMessage() {}

func (x *ChannelSubscribedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSubscribedEvent.ProtoReflect.Descriptor instead.
func (*ChannelSubscribedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{42}
}

func (x *ChannelSubscribedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelUnsubscribedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUnsubscribedEvent) Reset() {
	*x = ChannelUnsubscribedEvent{}
	mi := &file_channel_channel_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUnsubscribedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUnsubscribedEvent) ProtoMessage() {}

func (x *ChannelUnsubscribedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUnsubscribedEvent.ProtoReflect.Descriptor instead.
func (*ChannelUnsubscribedEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{43}
}

func (x *ChannelUnsubscribedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelPongEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelPongEvent) Reset() {
	*x = ChannelPongEvent{}
	mi := &file_channel_channel_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPongEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPongEvent) ProtoMessage() {}

func (x *ChannelPongEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPongEvent.ProtoReflect.Descriptor instead.
func (*ChannelPongEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{44}
}

type ChannelErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelErrorEvent) Reset() {
	*x = ChannelErrorEvent{}
	mi := &file_channel_channel_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelErrorEvent) ProtoMessage() {}

func (x *ChannelErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_channel_channel_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelErrorEvent.ProtoReflect.Descriptor instead.
func (*ChannelErrorEvent) Descriptor() ([]byte, []int) {
	return file_channel_channel_proto_rawDescGZIP(), []int{45}
}

func (x *ChannelErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ChannelErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChannelErrorEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_channel_channel_proto protoreflect.FileDescriptor

const file_channel_channel_proto_rawDesc = "" +
	"\n" +
	"\x15channel/channel.proto\x12\achannel\x1a\x13common/common.proto\"\x9f\x04\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x1b\n" +
	"\tadmin_ids\x18\x06 \x03(\tR\badminIds\x12)\n" +
	"\x10subscriber_count\x18\a \x01(\x03R\x0fsubscriberCount\x12\x1d\n" +
	"\n" +
	"post_count\x18\b \x01(\x03R\tpostCount\x120\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tupdatedAt\x12#\n" +
	"\ris_subscribed\x18\v \x01(\bR\fisSubscribed\x12\x19\n" +
	"\bis_admin\x18\f \x01(\bR\aisAdmin\x12\x19\n" +
	"\bis_owner\x18\r \x01(\bR\aisOwner\x125\n" +
	"\vpinned_post\x18\x0e \x01(\v2\x14.channel.ChannelPostR\n" +
	"pinnedPost\x12\x1a\n" +
	"\busername\x18\x0f \x01(\tR\busername\x12\x1b\n" +
	"\tis_public\x18\x10 \x01(\bR\bisPublic\"\xf0\x02\n" +
	"\vChannelPost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x05 \x03(\tR\tmediaUrls\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x03R\tviewCount\x120\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x11.common.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_pinned\x18\t \x01(\bR\bisPinned\x12\x1b\n" +
	"\tis_edited\x18\n" +
	" \x01(\bR\bisEdited\x12\x1f\n" +
	"\vauthor_name\x18\v \x01(\tR\n" +
	"authorName\"\x98\x01\n" +
	"\n" +
	"Subscriber\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x126\n" +
	"\rsubscribed_at\x18\x04 \x01(\v2\x11.common.TimestampR\fsubscribedAt\"\xa4\x01\n" +
	"\x05Admin\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x19\n" +
	"\bis_owner\x18\x04 \x01(\bR\aisOwner\x12,\n" +
	"\badded_at\x18\x05 \x01(\v2\x11.common.TimestampR\aaddedAt\"\xa4\x01\n" +
	"\x14CreateChannelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\"2\n" +
	"\x11GetChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\xc3\x01\n" +
	"\x14UpdateChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\"5\n" +
	"\x14DeleteChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"k\n" +
	"\x1cGetSubscribedChannelsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"f\n" +
	"\x17GetOwnedChannelsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"a\n" +
	"\x15SearchChannelsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"t\n" +
	"\x10ChannelsResponse\x12,\n" +
	"\bchannels\x18\x01 \x03(\v2\x10.channel.ChannelR\bchannels\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"3\n" +
	"\x12UnsubscribeRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"j\n" +
	"\x15GetSubscribersRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\x80\x01\n" +
	"\x13SubscribersResponse\x125\n" +
	"\vsubscribers\x18\x01 \x03(\v2\x13.channel.SubscriberR\vsubscribers\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"9\n" +
	"\x18CheckSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"@\n" +
	"\x19CheckSubscriptionResponse\x12#\n" +
	"\ris_subscribed\x18\x01 \x01(\bR\fisSubscribed\"I\n" +
	"\x0fAddAdminRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x12RemoveAdminRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x10GetAdminsRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"8\n" +
	"\x0eAdminsResponse\x12&\n" +
	"\x06admins\x18\x01 \x03(\v2\x0e.channel.AdminR\x06admins\"l\n" +
	"\x12PublishPostRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\"d\n" +
	"\x0fGetPostsRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\")\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"c\n" +
	"\x0fEditPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\",\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\")\n" +
	"\x0ePinPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"+\n" +
	"\x10UnpinPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"o\n" +
	"\rPostsResponse\x12*\n" +
	"\x05posts\x18\x01 \x03(\v2\x14.channel.ChannelPostR\x05posts\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xd4\x01\n" +
	"\x12ChannelClientEvent\x12>\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1e.channel.ChannelSubscribeEventH\x00R\tsubscribe\x12D\n" +
	"\vunsubscribe\x18\x02 \x01(\v2 .channel.ChannelUnsubscribeEventH\x00R\vunsubscribe\x12/\n" +
	"\x04ping\x18\x03 \x01(\v2\x19.channel.ChannelPingEventH\x00R\x04pingB\a\n" +
	"\x05event\"6\n" +
	"\x15ChannelSubscribeEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"8\n" +
	"\x17ChannelUnsubscribeEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x12\n" +
	"\x10ChannelPingEvent\"\xd1\x05\n" +
	"\x12ChannelServerEvent\x122\n" +
	"\bnew_post\x18\x01 \x01(\v2\x15.channel.NewPostEventH\x00R\anewPost\x12;\n" +
	"\vpost_edited\x18\x02 \x01(\v2\x18.channel.PostEditedEventH\x00R\n" +
	"postEdited\x12>\n" +
	"\fpost_deleted\x18\x03 \x01(\v2\x19.channel.PostDeletedEventH\x00R\vpostDeleted\x12;\n" +
	"\vpost_pinned\x18\x04 \x01(\v2\x18.channel.PostPinnedEventH\x00R\n" +
	"postPinned\x12A\n" +
	"\rpost_unpinned\x18\x05 \x01(\v2\x1a.channel.PostUnpinnedEventH\x00R\fpostUnpinned\x12G\n" +
	"\x0fchannel_updated\x18\x06 \x01(\v2\x1c.channel.ChannelUpdatedEventH\x00R\x0echannelUpdated\x12G\n" +
	"\x0fchannel_deleted\x18\a \x01(\v2\x1c.channel.ChannelDeletedEventH\x00R\x0echannelDeleted\x12A\n" +
	"\n" +
	"subscribed\x18\b \x01(\v2\x1f.channel.ChannelSubscribedEventH\x00R\n" +
	"subscribed\x12G\n" +
	"\funsubscribed\x18\t \x01(\v2!.channel.ChannelUnsubscribedEventH\x00R\funsubscribed\x12/\n" +
	"\x04pong\x18\n" +
	" \x01(\v2\x19.channel.ChannelPongEventH\x00R\x04pong\x122\n" +
	"\x05error\x18\v \x01(\v2\x1a.channel.ChannelErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"8\n" +
	"\fNewPostEvent\x12(\n" +
	"\x04post\x18\x01 \x01(\v2\x14.channel.ChannelPostR\x04post\";\n" +
	"\x0fPostEditedEvent\x12(\n" +
	"\x04post\x18\x01 \x01(\v2\x14.channel.ChannelPostR\x04post\"J\n" +
	"\x10PostDeletedEvent\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\";\n" +
	"\x0fPostPinnedEvent\x12(\n" +
	"\x04post\x18\x01 \x01(\v2\x14.channel.ChannelPostR\x04post\"K\n" +
	"\x11PostUnpinnedEvent\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"A\n" +
	"\x13ChannelUpdatedEvent\x12*\n" +
	"\achannel\x18\x01 \x01(\v2\x10.channel.ChannelR\achannel\"4\n" +
	"\x13ChannelDeletedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"7\n" +
	"\x16ChannelSubscribedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"9\n" +
	"\x18ChannelUnsubscribedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x12\n" +
	"\x10ChannelPongEvent\"Y\n" +
	"\x11ChannelErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2\xbf\v\n" +
	"\x0eChannelService\x12@\n" +
	"\rCreateChannel\x12\x1d.channel.CreateChannelRequest\x1a\x10.channel.Channel\x12:\n" +
	"\n" +
	"GetChannel\x12\x1a.channel.GetChannelRequest\x1a\x10.channel.Channel\x12@\n" +
	"\rUpdateChannel\x12\x1d.channel.UpdateChannelRequest\x1a\x10.channel.Channel\x12=\n" +
	"\rDeleteChannel\x12\x1d.channel.DeleteChannelRequest\x1a\r.common.Empty\x12Y\n" +
	"\x15GetSubscribedChannels\x12%.channel.GetSubscribedChannelsRequest\x1a\x19.channel.ChannelsResponse\x12O\n" +
	"\x10GetOwnedChannels\x12 .channel.GetOwnedChannelsRequest\x1a\x19.channel.ChannelsResponse\x12K\n" +
	"\x0eSearchChannels\x12\x1e.channel.SearchChannelsRequest\x1a\x19.channel.ChannelsResponse\x125\n" +
	"\tSubscribe\x12\x19.channel.SubscribeRequest\x1a\r.common.Empty\x129\n" +
	"\vUnsubscribe\x12\x1b.channel.UnsubscribeRequest\x1a\r.common.Empty\x12N\n" +
	"\x0eGetSubscribers\x12\x1e.channel.GetSubscribersRequest\x1a\x1c.channel.SubscribersResponse\x12Z\n" +
	"\x11CheckSubscription\x12!.channel.CheckSubscriptionRequest\x1a\".channel.CheckSubscriptionResponse\x123\n" +
	"\bAddAdmin\x12\x18.channel.AddAdminRequest\x1a\r.common.Empty\x129\n" +
	"\vRemoveAdmin\x12\x1b.channel.RemoveAdminRequest\x1a\r.common.Empty\x12?\n" +
	"\tGetAdmins\x12\x19.channel.GetAdminsRequest\x1a\x17.channel.AdminsResponse\x12@\n" +
	"\vPublishPost\x12\x1b.channel.PublishPostRequest\x1a\x14.channel.ChannelPost\x12<\n" +
	"\bGetPosts\x12\x18.channel.GetPostsRequest\x1a\x16.channel.PostsResponse\x128\n" +
	"\aGetPost\x12\x17.channel.GetPostRequest\x1a\x14.channel.ChannelPost\x12:\n" +
	"\bEditPost\x12\x18.channel.EditPostRequest\x1a\x14.channel.ChannelPost\x127\n" +
	"\n" +
	"DeletePost\x12\x1a.channel.DeletePostRequest\x1a\r.common.Empty\x121\n" +
	"\aPinPost\x12\x17.channel.PinPostRequest\x1a\r.common.Empty\x125\n" +
	"\tUnpinPost\x12\x19.channel.UnpinPostRequest\x1a\r.common.Empty\x12M\n" +
	"\rStreamUpdates\x12\x1b.channel.ChannelClientEvent\x1a\x1b.channel.ChannelServerEvent(\x010\x01B6Z4github.com/funcdfs/lesser/channel/gen_protos/channelb\x06proto3"

var (
	file_channel_channel_proto_rawDescOnce sync.Once
	file_channel_channel_proto_rawDescData []byte
)

func file_channel_channel_proto_rawDescGZIP() []byte {
	file_channel_channel_proto_rawDescOnce.Do(func() {
		file_channel_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_channel_proto_rawDesc), len(file_channel_channel_proto_rawDesc)))
	})
	return file_channel_channel_proto_rawDescData
}

var file_channel_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_channel_channel_proto_goTypes = []any{
	(*Channel)(nil),                      // 0: channel.Channel
	(*ChannelPost)(nil),                  // 1: channel.ChannelPost
	(*Subscriber)(nil),                   // 2: channel.Subscriber
	(*Admin)(nil),                        // 3: channel.Admin
	(*CreateChannelRequest)(nil),         // 4: channel.CreateChannelRequest
	(*GetChannelRequest)(nil),            // 5: channel.GetChannelRequest
	(*UpdateChannelRequest)(nil),         // 6: channel.UpdateChannelRequest
	(*DeleteChannelRequest)(nil),         // 7: channel.DeleteChannelRequest
	(*GetSubscribedChannelsRequest)(nil), // 8: channel.GetSubscribedChannelsRequest
	(*GetOwnedChannelsRequest)(nil),      // 9: channel.GetOwnedChannelsRequest
	(*SearchChannelsRequest)(nil),        // 10: channel.SearchChannelsRequest
	(*ChannelsResponse)(nil),             // 11: channel.ChannelsResponse
	(*SubscribeRequest)(nil),             // 12: channel.SubscribeRequest
	(*UnsubscribeRequest)(nil),           // 13: channel.UnsubscribeRequest
	(*GetSubscribersRequest)(nil),        // 14: channel.GetSubscribersRequest
	(*SubscribersResponse)(nil),          // 15: channel.SubscribersResponse
	(*CheckSubscriptionRequest)(nil),     // 16: channel.CheckSubscriptionRequest
	(*CheckSubscriptionResponse)(nil),    // 17: channel.CheckSubscriptionResponse
	(*AddAdminRequest)(nil),              // 18: channel.AddAdminRequest
	(*RemoveAdminRequest)(nil),           // 19: channel.RemoveAdminRequest
	(*GetAdminsRequest)(nil),             // 20: channel.GetAdminsRequest
	(*AdminsResponse)(nil),               // 21: channel.AdminsResponse
	(*PublishPostRequest)(nil),           // 22: channel.PublishPostRequest
	(*GetPostsRequest)(nil),              // 23: channel.GetPostsRequest
	(*GetPostRequest)(nil),               // 24: channel.GetPostRequest
	(*EditPostRequest)(nil),              // 25: channel.EditPostRequest
	(*DeletePostRequest)(nil),            // 26: channel.DeletePostRequest
	(*PinPostRequest)(nil),               // 27: channel.PinPostRequest
	(*UnpinPostRequest)(nil),             // 28: channel.UnpinPostRequest
	(*PostsResponse)(nil),                // 29: channel.PostsResponse
	(*ChannelClientEvent)(nil),           // 30: channel.ChannelClientEvent
	(*ChannelSubscribeEvent)(nil),        // 31: channel.ChannelSubscribeEvent
	(*ChannelUnsubscribeEvent)(nil),      // 32: channel.ChannelUnsubscribeEvent
	(*ChannelPingEvent)(nil),             // 33: channel.ChannelPingEvent
	(*ChannelServerEvent)(nil),           // 34: channel.ChannelServerEvent
	(*NewPostEvent)(nil),                 // 35: channel.NewPostEvent
	(*PostEditedEvent)(nil),              // 36: channel.PostEditedEvent
	(*PostDeletedEvent)(nil),             // 37: channel.PostDeletedEvent
	(*PostPinnedEvent)(nil),              // 38: channel.PostPinnedEvent
	(*PostUnpinnedEvent)(nil),            // 39: channel.PostUnpinnedEvent
	(*ChannelUpdatedEvent)(nil),          // 40: channel.ChannelUpdatedEvent
	(*ChannelDeletedEvent)(nil),          // 41: channel.ChannelDeletedEvent
	(*ChannelSubscribedEvent)(nil),       // 42: channel.ChannelSubscribedEvent
	(*ChannelUnsubscribedEvent)(nil),     // 43: channel.ChannelUnsubscribedEvent
	(*ChannelPongEvent)(nil),             // 44: channel.ChannelPongEvent
	(*ChannelErrorEvent)(nil),            // 45: channel.ChannelErrorEvent
	(*common.Timestamp)(nil),             // 46: common.Timestamp
	(*common.Pagination)(nil),            // 47: common.Pagination
	(*common.Empty)(nil),                 // 48: common.Empty
}
var file_channel_channel_proto_depIdxs = []int32{
	46, // 0: channel.Channel.created_at:type_name -> common.Timestamp
	46, // 1: channel.Channel.updated_at:type_name -> common.Timestamp
	1,  // 2: channel.Channel.pinned_post:type_name -> channel.ChannelPost
	46, // 3: channel.ChannelPost.created_at:type_name -> common.Timestamp
	46, // 4: channel.ChannelPost.updated_at:type_name -> common.Timestamp
	46, // 5: channel.Subscriber.subscribed_at:type_name -> common.Timestamp
	46, // 6: channel.Admin.added_at:type_name -> common.Timestamp
	47, // 7: channel.GetSubscribedChannelsRequest.pagination:type_name -> common.Pagination
	47, // 8: channel.GetOwnedChannelsRequest.pagination:type_name -> common.Pagination
	47, // 9: channel.SearchChannelsRequest.pagination:type_name -> common.Pagination
	0,  // 10: channel.ChannelsResponse.channels:type_name -> channel.Channel
	47, // 11: channel.ChannelsResponse.pagination:type_name -> common.Pagination
	47, // 12: channel.GetSubscribersRequest.pagination:type_name -> common.Pagination
	2,  // 13: channel.SubscribersResponse.subscribers:type_name -> channel.Subscriber
	47, // 14: channel.SubscribersResponse.pagination:type_name -> common.Pagination
	3,  // 15: channel.AdminsResponse.admins:type_name -> channel.Admin
	47, // 16: channel.GetPostsRequest.pagination:type_name -> common.Pagination
	1,  // 17: channel.PostsResponse.posts:type_name -> channel.ChannelPost
	47, // 18: channel.PostsResponse.pagination:type_name -> common.Pagination
	31, // 19: channel.ChannelClientEvent.subscribe:type_name -> channel.ChannelSubscribeEvent
	32, // 20: channel.ChannelClientEvent.unsubscribe:type_name -> channel.ChannelUnsubscribeEvent
	33, // 21: channel.ChannelClientEvent.ping:type_name -> channel.ChannelPingEvent
	35, // 22: channel.ChannelServerEvent.new_post:type_name -> channel.NewPostEvent
	36, // 23: channel.ChannelServerEvent.post_edited:type_name -> channel.PostEditedEvent
	37, // 24: channel.ChannelServerEvent.post_deleted:type_name -> channel.PostDeletedEvent
	38, // 25: channel.ChannelServerEvent.post_pinned:type_name -> channel.PostPinnedEvent
	39, // 26: channel.ChannelServerEvent.post_unpinned:type_name -> channel.PostUnpinnedEvent
	40, // 27: channel.ChannelServerEvent.channel_updated:type_name -> channel.ChannelUpdatedEvent
	41, // 28: channel.ChannelServerEvent.channel_deleted:type_name -> channel.ChannelDeletedEvent
	42, // 29: channel.ChannelServerEvent.subscribed:type_name -> channel.ChannelSubscribedEvent
	43, // 30: channel.ChannelServerEvent.unsubscribed:type_name -> channel.ChannelUnsubscribedEvent
	44, // 31: channel.ChannelServerEvent.pong:type_name -> channel.ChannelPongEvent
	45, // 32: channel.ChannelServerEvent.error:type_name -> channel.ChannelErrorEvent
	1,  // 33: channel.NewPostEvent.post:type_name -> channel.ChannelPost
	1,  // 34: channel.PostEditedEvent.post:type_name -> channel.ChannelPost
	1,  // 35: channel.PostPinnedEvent.post:type_name -> channel.ChannelPost
	0,  // 36: channel.ChannelUpdatedEvent.channel:type_name -> channel.Channel
	4,  // 37: channel.ChannelService.CreateChannel:input_type -> channel.CreateChannelRequest
	5,  // 38: channel.ChannelService.GetChannel:input_type -> channel.GetChannelRequest
	6,  // 39: channel.ChannelService.UpdateChannel:input_type -> channel.UpdateChannelRequest
	7,  // 40: channel.ChannelService.DeleteChannel:input_type -> channel.DeleteChannelRequest
	8,  // 41: channel.ChannelService.GetSubscribedChannels:input_type -> channel.GetSubscribedChannelsRequest
	9,  // 42: channel.ChannelService.GetOwnedChannels:input_type -> channel.GetOwnedChannelsRequest
	10, // 43: channel.ChannelService.SearchChannels:input_type -> channel.SearchChannelsRequest
	12, // 44: channel.ChannelService.Subscribe:input_type -> channel.SubscribeRequest
	13, // 45: channel.ChannelService.Unsubscribe:input_type -> channel.UnsubscribeRequest
	14, // 46: channel.ChannelService.GetSubscribers:input_type -> channel.GetSubscribersRequest
	16, // 47: channel.ChannelService.CheckSubscription:input_type -> channel.CheckSubscriptionRequest
	18, // 48: channel.ChannelService.AddAdmin:input_type -> channel.AddAdminRequest
	19, // 49: channel.ChannelService.RemoveAdmin:input_type -> channel.RemoveAdminRequest
	20, // 50: channel.ChannelService.GetAdmins:input_type -> channel.GetAdminsRequest
	22, // 51: channel.ChannelService.PublishPost:input_type -> channel.PublishPostRequest
	23, // 52: channel.ChannelService.GetPosts:input_type -> channel.GetPostsRequest
	24, // 53: channel.ChannelService.GetPost:input_type -> channel.GetPostRequest
	25, // 54: channel.ChannelService.EditPost:input_type -> channel.EditPostRequest
	26, // 55: channel.ChannelService.DeletePost:input_type -> channel.DeletePostRequest
	27, // 56: channel.ChannelService.PinPost:input_type -> channel.PinPostRequest
	28, // 57: channel.ChannelService.UnpinPost:input_type -> channel.UnpinPostRequest
	30, // 58: channel.ChannelService.StreamUpdates:input_type -> channel.ChannelClientEvent
	0,  // 59: channel.ChannelService.CreateChannel:output_type -> channel.Channel
	0,  // 60: channel.ChannelService.GetChannel:output_type -> channel.Channel
	0,  // 61: channel.ChannelService.UpdateChannel:output_type -> channel.Channel
	48, // 62: channel.ChannelService.DeleteChannel:output_type -> common.Empty
	11, // 63: channel.ChannelService.GetSubscribedChannels:output_type -> channel.ChannelsResponse
	11, // 64: channel.ChannelService.GetOwnedChannels:output_type -> channel.ChannelsResponse
	11, // 65: channel.ChannelService.SearchChannels:output_type -> channel.ChannelsResponse
	48, // 66: channel.ChannelService.Subscribe:output_type -> common.Empty
	48, // 67: channel.ChannelService.Unsubscribe:output_type -> common.Empty
	15, // 68: channel.ChannelService.GetSubscribers:output_type -> channel.SubscribersResponse
	17, // 69: channel.ChannelService.CheckSubscription:output_type -> channel.CheckSubscriptionResponse
	48, // 70: channel.ChannelService.AddAdmin:output_type -> common.Empty
	48, // 71: channel.ChannelService.RemoveAdmin:output_type -> common.Empty
	21, // 72: channel.ChannelService.GetAdmins:output_type -> channel.AdminsResponse
	1,  // 73: channel.ChannelService.PublishPost:output_type -> channel.ChannelPost
	29, // 74: channel.ChannelService.GetPosts:output_type -> channel.PostsResponse
	1,  // 75: channel.ChannelService.GetPost:output_type -> channel.ChannelPost
	1,  // 76: channel.ChannelService.EditPost:output_type -> channel.ChannelPost
	48, // 77: channel.ChannelService.DeletePost:output_type -> common.Empty
	48, // 78: channel.ChannelService.PinPost:output_type -> common.Empty
	48, // 79: channel.ChannelService.UnpinPost:output_type -> common.Empty
	34, // 80: channel.ChannelService.StreamUpdates:output_type -> channel.ChannelServerEvent
	59, // [59:81] is the sub-list for method output_type
	37, // [37:59] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_channel_channel_proto_init() }
func file_channel_channel_proto_init() {
	if File_channel_channel_proto != nil {
		return
	}
	file_channel_channel_proto_msgTypes[30].OneofWrappers = []any{
		(*ChannelClientEvent_Subscribe)(nil),
		(*ChannelClientEvent_Unsubscribe)(nil),
		(*ChannelClientEvent_Ping)(nil),
	}
	file_channel_channel_proto_msgTypes[34].OneofWrappers = []any{
		(*ChannelServerEvent_NewPost)(nil),
		(*ChannelServerEvent_PostEdited)(nil),
		(*ChannelServerEvent_PostDeleted)(nil),
		(*ChannelServerEvent_PostPinned)(nil),
		(*ChannelServerEvent_PostUnpinned)(nil),
		(*ChannelServerEvent_ChannelUpdated)(nil),
		(*ChannelServerEvent_ChannelDeleted)(nil),
		(*ChannelServerEvent_Subscribed)(nil),
		(*ChannelServerEvent_Unsubscribed)(nil),
		(*ChannelServerEvent_Pong)(nil),
		(*ChannelServerEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_channel_proto_rawDesc), len(file_channel_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_channel_proto_goTypes,
		DependencyIndexes: file_channel_channel_proto_depIdxs,
		MessageInfos:      file_channel_channel_proto_msgTypes,
	}.Build()
	File_channel_channel_proto = out.File
	file_channel_channel_proto_goTypes = nil
	file_channel_channel_proto_depIdxs = nil
}
