# Timeline Service - Development Dockerfile
FROM golang:1.23-alpine

WORKDIR /app/timeline

RUN apk add --no-cache git curl
RUN go install github.com/air-verse/air@latest

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

CMD ["air", "-c", ".air.toml"]
