# Generated by Django 6.0 on 2025-12-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_images_json_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reposts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
