FROM golang:1.24-alpine

RUN apk add --no-cache git ca-certificates tzdata curl

RUN go install github.com/air-verse/air@v1.61.7

WORKDIR /app

EXPOSE 8080 50052

CMD ["sh", "-c", "go mod tidy && air -c .air.toml"]
