FROM golang:1.25-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o search

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/search .
EXPOSE 7701
CMD ["./search"]
