// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: feed/feed.proto

package feed

import (
	common "github.com/funcdfs/lesser/gateway/proto/common"
	content "github.com/funcdfs/lesser/gateway/proto/content"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeedItem Feed 流中的单个条目
type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *content.Content       `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                // 内容详情
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`                // 当前用户是否已点赞
	IsBookmarked  bool                   `protobuf:"varint,3,opt,name=is_bookmarked,json=isBookmarked,proto3" json:"is_bookmarked,omitempty"` // 当前用户是否已收藏
	IsReposted    bool                   `protobuf:"varint,4,opt,name=is_reposted,json=isReposted,proto3" json:"is_reposted,omitempty"`       // 当前用户是否已转发
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedItem) GetContent() *content.Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FeedItem) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *FeedItem) GetIsBookmarked() bool {
	if x != nil {
		return x.IsBookmarked
	}
	return false
}

func (x *FeedItem) GetIsReposted() bool {
	if x != nil {
		return x.IsReposted
	}
	return false
}

// GetFollowingFeedRequest 获取关注用户 Feed 流请求
type GetFollowingFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户 ID
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingFeedRequest) Reset() {
	*x = GetFollowingFeedRequest{}
	mi := &file_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingFeedRequest) ProtoMessage() {}

func (x *GetFollowingFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingFeedRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetFollowingFeedResponse 获取关注用户 Feed 流响应
type GetFollowingFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingFeedResponse) Reset() {
	*x = GetFollowingFeedResponse{}
	mi := &file_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingFeedResponse) ProtoMessage() {}

func (x *GetFollowingFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingFeedResponse) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetFollowingFeedResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetRecommendFeedRequest 获取推荐 Feed 流请求（预留）
type GetRecommendFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户 ID（用于个性化推荐）
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendFeedRequest) Reset() {
	*x = GetRecommendFeedRequest{}
	mi := &file_feed_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedRequest) ProtoMessage() {}

func (x *GetRecommendFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendFeedRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetRecommendFeedResponse 获取推荐 Feed 流响应（预留）
type GetRecommendFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendFeedResponse) Reset() {
	*x = GetRecommendFeedResponse{}
	mi := &file_feed_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedResponse) ProtoMessage() {}

func (x *GetRecommendFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendFeedResponse) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRecommendFeedResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetUserFeedRequest 获取指定用户的 Feed（用户主页）
type GetUserFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 目标用户 ID
	ViewerId      string                 `protobuf:"bytes,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // 查看者 ID（用于计算点赞/收藏状态）
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedRequest) Reset() {
	*x = GetUserFeedRequest{}
	mi := &file_feed_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedRequest) ProtoMessage() {}

func (x *GetUserFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedRequest.ProtoReflect.Descriptor instead.
func (*GetUserFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFeedRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *GetUserFeedRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetUserFeedResponse 获取指定用户的 Feed 响应
type GetUserFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedResponse) Reset() {
	*x = GetUserFeedResponse{}
	mi := &file_feed_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedResponse) ProtoMessage() {}

func (x *GetUserFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedResponse.ProtoReflect.Descriptor instead.
func (*GetUserFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserFeedResponse) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetUserFeedResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Comment 评论实体
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 父评论 ID，用于回复
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *common.Timestamp      `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,9,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_feed_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{7}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Comment) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Comment) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

// Repost 转发实体
type Repost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Quote         string                 `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"` // 转发时的引用文字
	CreatedAt     *common.Timestamp      `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repost) Reset() {
	*x = Repost{}
	mi := &file_feed_feed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repost) ProtoMessage() {}

func (x *Repost) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repost.ProtoReflect.Descriptor instead.
func (*Repost) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{8}
}

func (x *Repost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Repost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Repost) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Repost) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Bookmark 收藏实体
type Bookmark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bookmark) Reset() {
	*x = Bookmark{}
	mi := &file_feed_feed_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookmark) ProtoMessage() {}

func (x *Bookmark) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookmark.ProtoReflect.Descriptor instead.
func (*Bookmark) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{9}
}

func (x *Bookmark) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bookmark) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bookmark) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Bookmark) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// LikeRequest 点赞请求
type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_feed_feed_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{10}
}

func (x *LikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// UnlikeRequest 取消点赞请求
type UnlikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeRequest) Reset() {
	*x = UnlikeRequest{}
	mi := &file_feed_feed_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeRequest) ProtoMessage() {}

func (x *UnlikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeRequest.ProtoReflect.Descriptor instead.
func (*UnlikeRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{11}
}

func (x *UnlikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnlikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// CreateCommentRequest 创建评论请求
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 可选，回复评论时使用
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_feed_feed_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCommentRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// DeleteCommentRequest 删除评论请求
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用于验证权限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_feed_feed_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListCommentsRequest 获取评论列表请求
type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 可选，获取某评论的回复
	Pagination    *common.Pagination     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_feed_feed_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{14}
}

func (x *ListCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ListCommentsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListCommentsRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListCommentsResponse 评论列表响应
type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_feed_feed_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{15}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// RepostRequest 转发请求
type RepostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Quote         string                 `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"` // 可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepostRequest) Reset() {
	*x = RepostRequest{}
	mi := &file_feed_feed_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostRequest) ProtoMessage() {}

func (x *RepostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostRequest.ProtoReflect.Descriptor instead.
func (*RepostRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{16}
}

func (x *RepostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RepostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *RepostRequest) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

// BookmarkRequest 收藏请求
type BookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookmarkRequest) Reset() {
	*x = BookmarkRequest{}
	mi := &file_feed_feed_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkRequest) ProtoMessage() {}

func (x *BookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkRequest.ProtoReflect.Descriptor instead.
func (*BookmarkRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{17}
}

func (x *BookmarkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookmarkRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// UnbookmarkRequest 取消收藏请求
type UnbookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbookmarkRequest) Reset() {
	*x = UnbookmarkRequest{}
	mi := &file_feed_feed_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbookmarkRequest) ProtoMessage() {}

func (x *UnbookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbookmarkRequest.ProtoReflect.Descriptor instead.
func (*UnbookmarkRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{18}
}

func (x *UnbookmarkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnbookmarkRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// ListBookmarksRequest 获取收藏列表请求
type ListBookmarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksRequest) Reset() {
	*x = ListBookmarksRequest{}
	mi := &file_feed_feed_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksRequest) ProtoMessage() {}

func (x *ListBookmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksRequest.ProtoReflect.Descriptor instead.
func (*ListBookmarksRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{19}
}

func (x *ListBookmarksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListBookmarksRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListBookmarksResponse 收藏列表响应
type ListBookmarksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookmarks     []*Bookmark            `protobuf:"bytes,1,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksResponse) Reset() {
	*x = ListBookmarksResponse{}
	mi := &file_feed_feed_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksResponse) ProtoMessage() {}

func (x *ListBookmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksResponse.ProtoReflect.Descriptor instead.
func (*ListBookmarksResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{20}
}

func (x *ListBookmarksResponse) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

func (x *ListBookmarksResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_feed_feed_proto protoreflect.FileDescriptor

const file_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x0ffeed/feed.proto\x12\x04feed\x1a\x13common/common.proto\x1a\x15content/content.proto\"\x97\x01\n" +
	"\bFeedItem\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.content.ContentR\acontent\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\x12#\n" +
	"\ris_bookmarked\x18\x03 \x01(\bR\fisBookmarked\x12\x1f\n" +
	"\vis_reposted\x18\x04 \x01(\bR\n" +
	"isReposted\"f\n" +
	"\x17GetFollowingFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"t\n" +
	"\x18GetFollowingFeedResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"f\n" +
	"\x17GetRecommendFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"t\n" +
	"\x18GetRecommendFeedResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"~\n" +
	"\x12GetUserFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\tR\bviewerId\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"o\n" +
	"\x13GetUserFeedResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"\xaa\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x120\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x11.common.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vreply_count\x18\t \x01(\x05R\n" +
	"replyCount\"\x92\x01\n" +
	"\x06Repost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x14\n" +
	"\x05quote\x18\x04 \x01(\tR\x05quote\x120\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x11.common.TimestampR\tcreatedAt\"~\n" +
	"\bBookmark\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x120\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x11.common.TimestampR\tcreatedAt\"?\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"A\n" +
	"\rUnlikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"\x83\x01\n" +
	"\x14CreateCommentRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"N\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x7f\n" +
	"\x13ListCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x122\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"u\n" +
	"\x14ListCommentsResponse\x12)\n" +
	"\bcomments\x18\x01 \x03(\v2\r.feed.CommentR\bcomments\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"W\n" +
	"\rRepostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x14\n" +
	"\x05quote\x18\x03 \x01(\tR\x05quote\"C\n" +
	"\x0fBookmarkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"E\n" +
	"\x11UnbookmarkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"c\n" +
	"\x14ListBookmarksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\"y\n" +
	"\x15ListBookmarksResponse\x12,\n" +
	"\tbookmarks\x18\x01 \x03(\v2\x0e.feed.BookmarkR\tbookmarks\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.common.PaginationR\n" +
	"pagination2\xf3\x05\n" +
	"\vFeedService\x12Q\n" +
	"\x10GetFollowingFeed\x12\x1d.feed.GetFollowingFeedRequest\x1a\x1e.feed.GetFollowingFeedResponse\x12Q\n" +
	"\x10GetRecommendFeed\x12\x1d.feed.GetRecommendFeedRequest\x1a\x1e.feed.GetRecommendFeedResponse\x12B\n" +
	"\vGetUserFeed\x12\x18.feed.GetUserFeedRequest\x1a\x19.feed.GetUserFeedResponse\x12(\n" +
	"\x04Like\x12\x11.feed.LikeRequest\x1a\r.common.Empty\x12,\n" +
	"\x06Unlike\x12\x13.feed.UnlikeRequest\x1a\r.common.Empty\x12:\n" +
	"\rCreateComment\x12\x1a.feed.CreateCommentRequest\x1a\r.feed.Comment\x12:\n" +
	"\rDeleteComment\x12\x1a.feed.DeleteCommentRequest\x1a\r.common.Empty\x12E\n" +
	"\fListComments\x12\x19.feed.ListCommentsRequest\x1a\x1a.feed.ListCommentsResponse\x121\n" +
	"\fCreateRepost\x12\x13.feed.RepostRequest\x1a\f.feed.Repost\x120\n" +
	"\bBookmark\x12\x15.feed.BookmarkRequest\x1a\r.common.Empty\x124\n" +
	"\n" +
	"Unbookmark\x12\x17.feed.UnbookmarkRequest\x1a\r.common.Empty\x12H\n" +
	"\rListBookmarks\x12\x1a.feed.ListBookmarksRequest\x1a\x1b.feed.ListBookmarksResponseB+Z)github.com/funcdfs/lesser/feed/proto/feedb\x06proto3"

var (
	file_feed_feed_proto_rawDescOnce sync.Once
	file_feed_feed_proto_rawDescData []byte
)

func file_feed_feed_proto_rawDescGZIP() []byte {
	file_feed_feed_proto_rawDescOnce.Do(func() {
		file_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_feed_proto_rawDesc), len(file_feed_feed_proto_rawDesc)))
	})
	return file_feed_feed_proto_rawDescData
}

var file_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_feed_feed_proto_goTypes = []any{
	(*FeedItem)(nil),                 // 0: feed.FeedItem
	(*GetFollowingFeedRequest)(nil),  // 1: feed.GetFollowingFeedRequest
	(*GetFollowingFeedResponse)(nil), // 2: feed.GetFollowingFeedResponse
	(*GetRecommendFeedRequest)(nil),  // 3: feed.GetRecommendFeedRequest
	(*GetRecommendFeedResponse)(nil), // 4: feed.GetRecommendFeedResponse
	(*GetUserFeedRequest)(nil),       // 5: feed.GetUserFeedRequest
	(*GetUserFeedResponse)(nil),      // 6: feed.GetUserFeedResponse
	(*Comment)(nil),                  // 7: feed.Comment
	(*Repost)(nil),                   // 8: feed.Repost
	(*Bookmark)(nil),                 // 9: feed.Bookmark
	(*LikeRequest)(nil),              // 10: feed.LikeRequest
	(*UnlikeRequest)(nil),            // 11: feed.UnlikeRequest
	(*CreateCommentRequest)(nil),     // 12: feed.CreateCommentRequest
	(*DeleteCommentRequest)(nil),     // 13: feed.DeleteCommentRequest
	(*ListCommentsRequest)(nil),      // 14: feed.ListCommentsRequest
	(*ListCommentsResponse)(nil),     // 15: feed.ListCommentsResponse
	(*RepostRequest)(nil),            // 16: feed.RepostRequest
	(*BookmarkRequest)(nil),          // 17: feed.BookmarkRequest
	(*UnbookmarkRequest)(nil),        // 18: feed.UnbookmarkRequest
	(*ListBookmarksRequest)(nil),     // 19: feed.ListBookmarksRequest
	(*ListBookmarksResponse)(nil),    // 20: feed.ListBookmarksResponse
	(*content.Content)(nil),          // 21: content.Content
	(*common.Pagination)(nil),        // 22: common.Pagination
	(*common.Timestamp)(nil),         // 23: common.Timestamp
	(*common.Empty)(nil),             // 24: common.Empty
}
var file_feed_feed_proto_depIdxs = []int32{
	21, // 0: feed.FeedItem.content:type_name -> content.Content
	22, // 1: feed.GetFollowingFeedRequest.pagination:type_name -> common.Pagination
	0,  // 2: feed.GetFollowingFeedResponse.items:type_name -> feed.FeedItem
	22, // 3: feed.GetFollowingFeedResponse.pagination:type_name -> common.Pagination
	22, // 4: feed.GetRecommendFeedRequest.pagination:type_name -> common.Pagination
	0,  // 5: feed.GetRecommendFeedResponse.items:type_name -> feed.FeedItem
	22, // 6: feed.GetRecommendFeedResponse.pagination:type_name -> common.Pagination
	22, // 7: feed.GetUserFeedRequest.pagination:type_name -> common.Pagination
	0,  // 8: feed.GetUserFeedResponse.items:type_name -> feed.FeedItem
	22, // 9: feed.GetUserFeedResponse.pagination:type_name -> common.Pagination
	23, // 10: feed.Comment.created_at:type_name -> common.Timestamp
	23, // 11: feed.Comment.updated_at:type_name -> common.Timestamp
	23, // 12: feed.Repost.created_at:type_name -> common.Timestamp
	23, // 13: feed.Bookmark.created_at:type_name -> common.Timestamp
	22, // 14: feed.ListCommentsRequest.pagination:type_name -> common.Pagination
	7,  // 15: feed.ListCommentsResponse.comments:type_name -> feed.Comment
	22, // 16: feed.ListCommentsResponse.pagination:type_name -> common.Pagination
	22, // 17: feed.ListBookmarksRequest.pagination:type_name -> common.Pagination
	9,  // 18: feed.ListBookmarksResponse.bookmarks:type_name -> feed.Bookmark
	22, // 19: feed.ListBookmarksResponse.pagination:type_name -> common.Pagination
	1,  // 20: feed.FeedService.GetFollowingFeed:input_type -> feed.GetFollowingFeedRequest
	3,  // 21: feed.FeedService.GetRecommendFeed:input_type -> feed.GetRecommendFeedRequest
	5,  // 22: feed.FeedService.GetUserFeed:input_type -> feed.GetUserFeedRequest
	10, // 23: feed.FeedService.Like:input_type -> feed.LikeRequest
	11, // 24: feed.FeedService.Unlike:input_type -> feed.UnlikeRequest
	12, // 25: feed.FeedService.CreateComment:input_type -> feed.CreateCommentRequest
	13, // 26: feed.FeedService.DeleteComment:input_type -> feed.DeleteCommentRequest
	14, // 27: feed.FeedService.ListComments:input_type -> feed.ListCommentsRequest
	16, // 28: feed.FeedService.CreateRepost:input_type -> feed.RepostRequest
	17, // 29: feed.FeedService.Bookmark:input_type -> feed.BookmarkRequest
	18, // 30: feed.FeedService.Unbookmark:input_type -> feed.UnbookmarkRequest
	19, // 31: feed.FeedService.ListBookmarks:input_type -> feed.ListBookmarksRequest
	2,  // 32: feed.FeedService.GetFollowingFeed:output_type -> feed.GetFollowingFeedResponse
	4,  // 33: feed.FeedService.GetRecommendFeed:output_type -> feed.GetRecommendFeedResponse
	6,  // 34: feed.FeedService.GetUserFeed:output_type -> feed.GetUserFeedResponse
	24, // 35: feed.FeedService.Like:output_type -> common.Empty
	24, // 36: feed.FeedService.Unlike:output_type -> common.Empty
	7,  // 37: feed.FeedService.CreateComment:output_type -> feed.Comment
	24, // 38: feed.FeedService.DeleteComment:output_type -> common.Empty
	15, // 39: feed.FeedService.ListComments:output_type -> feed.ListCommentsResponse
	8,  // 40: feed.FeedService.CreateRepost:output_type -> feed.Repost
	24, // 41: feed.FeedService.Bookmark:output_type -> common.Empty
	24, // 42: feed.FeedService.Unbookmark:output_type -> common.Empty
	20, // 43: feed.FeedService.ListBookmarks:output_type -> feed.ListBookmarksResponse
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_feed_feed_proto_init() }
func file_feed_feed_proto_init() {
	if File_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_feed_proto_rawDesc), len(file_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_feed_proto_goTypes,
		DependencyIndexes: file_feed_feed_proto_depIdxs,
		MessageInfos:      file_feed_feed_proto_msgTypes,
	}.Build()
	File_feed_feed_proto = out.File
	file_feed_feed_proto_goTypes = nil
	file_feed_feed_proto_depIdxs = nil
}
