events {}

http {
  upstream django {
    server django:8000;
  }

  upstream go_search {
    server go-search:7701;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://django;
    }

    location /search/ {
      proxy_pass http://go_search;
    }
  }
}
