// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action 操作类型枚举
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	// Auth (1-9) - 已迁移到同步 RPC
	Action_USER_REGISTER Action = 1 // [DEPRECATED] 使用 Register RPC
	Action_USER_LOGIN    Action = 2 // [DEPRECATED] 使用 Login RPC
	Action_USER_LOGOUT   Action = 3
	// Post (10-19)
	// Command: POST_CREATE, POST_DELETE, POST_UPDATE
	// Query: POST_GET, POST_LIST
	Action_POST_CREATE Action = 10 // Command
	Action_POST_GET    Action = 11 // Query
	Action_POST_LIST   Action = 12 // Query
	Action_POST_DELETE Action = 13 // Command
	Action_POST_UPDATE Action = 14 // Command
	// Feed (20-29)
	// Command: FEED_LIKE, FEED_UNLIKE, FEED_COMMENT, FEED_COMMENT_DELETE, FEED_REPOST, FEED_BOOKMARK, FEED_UNBOOKMARK
	// Query: (none)
	Action_FEED_LIKE           Action = 20 // Command
	Action_FEED_UNLIKE         Action = 21 // Command
	Action_FEED_COMMENT        Action = 22 // Command
	Action_FEED_COMMENT_DELETE Action = 23 // Command
	Action_FEED_REPOST         Action = 24 // Command
	Action_FEED_BOOKMARK       Action = 25 // Command
	Action_FEED_UNBOOKMARK     Action = 26 // Command
	// Notification (30-39)
	// Command: NOTIFICATION_READ, NOTIFICATION_READ_ALL
	// Query: NOTIFICATION_LIST
	Action_NOTIFICATION_LIST     Action = 30 // Query
	Action_NOTIFICATION_READ     Action = 31 // Command
	Action_NOTIFICATION_READ_ALL Action = 32 // Command
	// User (40-49)
	// Command: USER_PROFILE_UPDATE, USER_FOLLOW, USER_UNFOLLOW
	// Query: USER_PROFILE_GET, USER_FOLLOWERS, USER_FOLLOWING
	Action_USER_PROFILE_GET    Action = 40 // Query
	Action_USER_PROFILE_UPDATE Action = 41 // Command
	Action_USER_FOLLOW         Action = 42 // Command
	Action_USER_UNFOLLOW       Action = 43 // Command
	Action_USER_FOLLOWERS      Action = 44 // Query
	Action_USER_FOLLOWING      Action = 45 // Query
	// Search (50-59)
	// Query: SEARCH_POSTS, SEARCH_USERS
	Action_SEARCH_POSTS Action = 50 // Query
	Action_SEARCH_USERS Action = 51 // Query
	// Chat (60-69) - 已迁移到 Chat Service gRPC
	// Command: CHAT_SEND, CHAT_CREATE_CONVERSATION, CHAT_MARK_READ
	// Query: CHAT_GET_CONVERSATIONS, CHAT_GET_MESSAGES
	Action_CHAT_SEND                Action = 60 // Command [DEPRECATED] 使用 Chat Service gRPC
	Action_CHAT_GET_CONVERSATIONS   Action = 61 // Query [DEPRECATED] 使用 Chat Service gRPC
	Action_CHAT_GET_MESSAGES        Action = 62 // Query [DEPRECATED] 使用 Chat Service gRPC
	Action_CHAT_CREATE_CONVERSATION Action = 63 // Command [DEPRECATED] 使用 Chat Service gRPC
	Action_CHAT_MARK_READ           Action = 64 // Command [DEPRECATED] 使用 Chat Service gRPC
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "ACTION_UNSPECIFIED",
		1:  "USER_REGISTER",
		2:  "USER_LOGIN",
		3:  "USER_LOGOUT",
		10: "POST_CREATE",
		11: "POST_GET",
		12: "POST_LIST",
		13: "POST_DELETE",
		14: "POST_UPDATE",
		20: "FEED_LIKE",
		21: "FEED_UNLIKE",
		22: "FEED_COMMENT",
		23: "FEED_COMMENT_DELETE",
		24: "FEED_REPOST",
		25: "FEED_BOOKMARK",
		26: "FEED_UNBOOKMARK",
		30: "NOTIFICATION_LIST",
		31: "NOTIFICATION_READ",
		32: "NOTIFICATION_READ_ALL",
		40: "USER_PROFILE_GET",
		41: "USER_PROFILE_UPDATE",
		42: "USER_FOLLOW",
		43: "USER_UNFOLLOW",
		44: "USER_FOLLOWERS",
		45: "USER_FOLLOWING",
		50: "SEARCH_POSTS",
		51: "SEARCH_USERS",
		60: "CHAT_SEND",
		61: "CHAT_GET_CONVERSATIONS",
		62: "CHAT_GET_MESSAGES",
		63: "CHAT_CREATE_CONVERSATION",
		64: "CHAT_MARK_READ",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":       0,
		"USER_REGISTER":            1,
		"USER_LOGIN":               2,
		"USER_LOGOUT":              3,
		"POST_CREATE":              10,
		"POST_GET":                 11,
		"POST_LIST":                12,
		"POST_DELETE":              13,
		"POST_UPDATE":              14,
		"FEED_LIKE":                20,
		"FEED_UNLIKE":              21,
		"FEED_COMMENT":             22,
		"FEED_COMMENT_DELETE":      23,
		"FEED_REPOST":              24,
		"FEED_BOOKMARK":            25,
		"FEED_UNBOOKMARK":          26,
		"NOTIFICATION_LIST":        30,
		"NOTIFICATION_READ":        31,
		"NOTIFICATION_READ_ALL":    32,
		"USER_PROFILE_GET":         40,
		"USER_PROFILE_UPDATE":      41,
		"USER_FOLLOW":              42,
		"USER_UNFOLLOW":            43,
		"USER_FOLLOWERS":           44,
		"USER_FOLLOWING":           45,
		"SEARCH_POSTS":             50,
		"SEARCH_USERS":             51,
		"CHAT_SEND":                60,
		"CHAT_GET_CONVERSATIONS":   61,
		"CHAT_GET_MESSAGES":        62,
		"CHAT_CREATE_CONVERSATION": 63,
		"CHAT_MARK_READ":           64,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_gateway_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_gateway_gateway_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

// ActionType 操作类型分类
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_COMMAND                 ActionType = 1 // 写操作，发布到 MQ 异步处理
	ActionType_QUERY                   ActionType = 2 // 读操作，直接查询返回
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "COMMAND",
		2: "QUERY",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"COMMAND":                 1,
		"QUERY":                   2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_gateway_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_gateway_gateway_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

// TaskStatus 任务状态
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_PENDING                 TaskStatus = 1 // 等待处理
	TaskStatus_PROCESSING              TaskStatus = 2 // 处理中
	TaskStatus_COMPLETED               TaskStatus = 3 // 已完成
	TaskStatus_FAILED                  TaskStatus = 4 // 失败
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PROCESSING",
		3: "COMPLETED",
		4: "FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"PENDING":                 1,
		"PROCESSING":              2,
		"COMPLETED":               3,
		"FAILED":                  4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_gateway_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_gateway_gateway_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

// LoginRequest 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RefreshTokenRequest 刷新 Token 请求
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// AuthResponse 认证响应
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GatewayRequest 统一网关请求
type GatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=gateway.Action" json:"action,omitempty"`   // 操作类型
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                      // API 版本，如 "1.0"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // 序列化的具体请求 (RegisterRequest/LoginRequest 等)
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求唯一标识，客户端生成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRequest) Reset() {
	*x = GatewayRequest{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRequest) ProtoMessage() {}

func (x *GatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRequest.ProtoReflect.Descriptor instead.
func (*GatewayRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *GatewayRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GatewayRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// GatewayResponse 统一网关响应
type GatewayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`          // 请求唯一标识
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`                            // 是否接受处理
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`          // 错误码（如有）
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（如有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GatewayResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *GatewayResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GatewayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetResultRequest 获取任务结果请求
type GetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultRequest) Reset() {
	*x = GetResultRequest{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRequest) ProtoMessage() {}

func (x *GetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRequest.ProtoReflect.Descriptor instead.
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetResultRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// TaskResult 任务处理结果
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`          // 请求唯一标识
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                              // 是否成功
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                               // 序列化的具体响应 (AuthResponse 等)
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`          // 错误码（如有）
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（如有）
	Status        TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=gateway.TaskStatus" json:"status,omitempty"`        // 任务状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_gateway_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_gateway_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

var File_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/gateway/gateway.proto\x12\agateway\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xcd\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x8c\x01\n" +
	"\x0eGatewayRequest\x12'\n" +
	"\x06action\x18\x01 \x01(\x0e2\x0f.gateway.ActionR\x06action\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x90\x01\n" +
	"\x0fGatewayResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"1\n" +
	"\x10GetResultRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xd0\x01\n" +
	"\n" +
	"TaskResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12+\n" +
	"\x06status\x18\x06 \x01(\x0e2\x13.gateway.TaskStatusR\x06status*\x84\x05\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rUSER_REGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"USER_LOGIN\x10\x02\x12\x0f\n" +
	"\vUSER_LOGOUT\x10\x03\x12\x0f\n" +
	"\vPOST_CREATE\x10\n" +
	"\x12\f\n" +
	"\bPOST_GET\x10\v\x12\r\n" +
	"\tPOST_LIST\x10\f\x12\x0f\n" +
	"\vPOST_DELETE\x10\r\x12\x0f\n" +
	"\vPOST_UPDATE\x10\x0e\x12\r\n" +
	"\tFEED_LIKE\x10\x14\x12\x0f\n" +
	"\vFEED_UNLIKE\x10\x15\x12\x10\n" +
	"\fFEED_COMMENT\x10\x16\x12\x17\n" +
	"\x13FEED_COMMENT_DELETE\x10\x17\x12\x0f\n" +
	"\vFEED_REPOST\x10\x18\x12\x11\n" +
	"\rFEED_BOOKMARK\x10\x19\x12\x13\n" +
	"\x0fFEED_UNBOOKMARK\x10\x1a\x12\x15\n" +
	"\x11NOTIFICATION_LIST\x10\x1e\x12\x15\n" +
	"\x11NOTIFICATION_READ\x10\x1f\x12\x19\n" +
	"\x15NOTIFICATION_READ_ALL\x10 \x12\x14\n" +
	"\x10USER_PROFILE_GET\x10(\x12\x17\n" +
	"\x13USER_PROFILE_UPDATE\x10)\x12\x0f\n" +
	"\vUSER_FOLLOW\x10*\x12\x11\n" +
	"\rUSER_UNFOLLOW\x10+\x12\x12\n" +
	"\x0eUSER_FOLLOWERS\x10,\x12\x12\n" +
	"\x0eUSER_FOLLOWING\x10-\x12\x10\n" +
	"\fSEARCH_POSTS\x102\x12\x10\n" +
	"\fSEARCH_USERS\x103\x12\r\n" +
	"\tCHAT_SEND\x10<\x12\x1a\n" +
	"\x16CHAT_GET_CONVERSATIONS\x10=\x12\x15\n" +
	"\x11CHAT_GET_MESSAGES\x10>\x12\x1c\n" +
	"\x18CHAT_CREATE_CONVERSATION\x10?\x12\x12\n" +
	"\x0eCHAT_MARK_READ\x10@*A\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOMMAND\x10\x01\x12\t\n" +
	"\x05QUERY\x10\x02*a\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xc4\x02\n" +
	"\x0eGatewayService\x12<\n" +
	"\aProcess\x12\x17.gateway.GatewayRequest\x1a\x18.gateway.GatewayResponse\x12;\n" +
	"\tGetResult\x12\x19.gateway.GetResultRequest\x1a\x13.gateway.TaskResult\x125\n" +
	"\x05Login\x12\x15.gateway.LoginRequest\x1a\x15.gateway.AuthResponse\x12;\n" +
	"\bRegister\x12\x18.gateway.RegisterRequest\x1a\x15.gateway.AuthResponse\x12C\n" +
	"\fRefreshToken\x12\x1c.gateway.RefreshTokenRequest\x1a\x15.gateway.AuthResponseB)Z'github.com/lesser/gateway/proto/gatewayb\x06proto3"

var (
	file_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_gateway_proto_rawDescData []byte
)

func file_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_gateway_proto_rawDesc), len(file_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_gateway_proto_rawDescData
}

var file_proto_gateway_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_gateway_gateway_proto_goTypes = []any{
	(Action)(0),                 // 0: gateway.Action
	(ActionType)(0),             // 1: gateway.ActionType
	(TaskStatus)(0),             // 2: gateway.TaskStatus
	(*LoginRequest)(nil),        // 3: gateway.LoginRequest
	(*RegisterRequest)(nil),     // 4: gateway.RegisterRequest
	(*RefreshTokenRequest)(nil), // 5: gateway.RefreshTokenRequest
	(*AuthResponse)(nil),        // 6: gateway.AuthResponse
	(*GatewayRequest)(nil),      // 7: gateway.GatewayRequest
	(*GatewayResponse)(nil),     // 8: gateway.GatewayResponse
	(*GetResultRequest)(nil),    // 9: gateway.GetResultRequest
	(*TaskResult)(nil),          // 10: gateway.TaskResult
}
var file_proto_gateway_gateway_proto_depIdxs = []int32{
	0,  // 0: gateway.GatewayRequest.action:type_name -> gateway.Action
	2,  // 1: gateway.TaskResult.status:type_name -> gateway.TaskStatus
	7,  // 2: gateway.GatewayService.Process:input_type -> gateway.GatewayRequest
	9,  // 3: gateway.GatewayService.GetResult:input_type -> gateway.GetResultRequest
	3,  // 4: gateway.GatewayService.Login:input_type -> gateway.LoginRequest
	4,  // 5: gateway.GatewayService.Register:input_type -> gateway.RegisterRequest
	5,  // 6: gateway.GatewayService.RefreshToken:input_type -> gateway.RefreshTokenRequest
	8,  // 7: gateway.GatewayService.Process:output_type -> gateway.GatewayResponse
	10, // 8: gateway.GatewayService.GetResult:output_type -> gateway.TaskResult
	6,  // 9: gateway.GatewayService.Login:output_type -> gateway.AuthResponse
	6,  // 10: gateway.GatewayService.Register:output_type -> gateway.AuthResponse
	6,  // 11: gateway.GatewayService.RefreshToken:output_type -> gateway.AuthResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gateway_gateway_proto_init() }
func file_proto_gateway_gateway_proto_init() {
	if File_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_gateway_proto_rawDesc), len(file_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_gateway_proto_depIdxs,
		EnumInfos:         file_proto_gateway_gateway_proto_enumTypes,
		MessageInfos:      file_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_gateway_proto = out.File
	file_proto_gateway_gateway_proto_goTypes = nil
	file_proto_gateway_gateway_proto_depIdxs = nil
}
