package grpc

// This file contains stub types that would normally be generated from proto files.
// In production, run `make proto` to generate these from protos/chat/chat.proto

import (
	"context"

	"google.golang.org/grpc"
)

// ConversationType enum
type ConversationType int32

const (
	ConversationType_PRIVATE ConversationType = 0
	ConversationType_GROUP   ConversationType = 1
	ConversationType_CHANNEL ConversationType = 2
)

// Timestamp message
type Timestamp struct {
	Seconds int64
	Nanos   int32
}

// Pagination message
type Pagination struct {
	Page     int32
	PageSize int32
	Total    int32
}

func (p *Pagination) GetPage() int32 {
	if p == nil {
		return 0
	}
	return p.Page
}

func (p *Pagination) GetPageSize() int32 {
	if p == nil {
		return 0
	}
	return p.PageSize
}

// Conversation message
type Conversation struct {
	Id          string
	Type        ConversationType
	Name        string
	MemberIds   []string
	CreatorId   string
	CreatedAt   *Timestamp
	LastMessage *Message
}

// Message message
type Message struct {
	Id             string
	ConversationId string
	SenderId       string
	Content        string
	MessageType    string
	CreatedAt      *Timestamp
}

// Request/Response messages

type GetConversationsRequest struct {
	UserId     string
	Pagination *Pagination
}

type ConversationsResponse struct {
	Conversations []*Conversation
	Pagination    *Pagination
}

type GetConversationRequest struct {
	ConversationId string
}

type CreateConversationRequest struct {
	Type      ConversationType
	Name      string
	MemberIds []string
	CreatorId string
}

type GetMessagesRequest struct {
	ConversationId string
	Pagination     *Pagination
}

type MessagesResponse struct {
	Messages   []*Message
	Pagination *Pagination
}

type SendMessageRequest struct {
	ConversationId string
	SenderId       string
	Content        string
	MessageType    string
}

type StreamRequest struct {
	UserId string
}

// ChatServiceServer interface
type ChatServiceServer interface {
	GetConversations(context.Context, *GetConversationsRequest) (*ConversationsResponse, error)
	GetConversation(context.Context, *GetConversationRequest) (*Conversation, error)
	CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error)
	GetMessages(context.Context, *GetMessagesRequest) (*MessagesResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*Message, error)
	StreamMessages(*StreamRequest, ChatService_StreamMessagesServer) error
}

// ChatService_StreamMessagesServer interface
type ChatService_StreamMessagesServer interface {
	Send(*Message) error
	grpc.ServerStream
}

// UnimplementedChatServiceServer for forward compatibility
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) GetConversations(context.Context, *GetConversationsRequest) (*ConversationsResponse, error) {
	return nil, nil
}

func (UnimplementedChatServiceServer) GetConversation(context.Context, *GetConversationRequest) (*Conversation, error) {
	return nil, nil
}

func (UnimplementedChatServiceServer) CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error) {
	return nil, nil
}

func (UnimplementedChatServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*MessagesResponse, error) {
	return nil, nil
}

func (UnimplementedChatServiceServer) SendMessage(context.Context, *SendMessageRequest) (*Message, error) {
	return nil, nil
}

func (UnimplementedChatServiceServer) StreamMessages(*StreamRequest, ChatService_StreamMessagesServer) error {
	return nil
}

// RegisterChatServiceServer registers the server
func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	// In production, this would be generated by protoc-gen-go-grpc
	// For now, we use a manual registration
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

// ChatService_ServiceDesc is the service descriptor
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversations",
			Handler:    _ChatService_GetConversations_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _ChatService_GetConversation_Handler,
		},
		{
			MethodName: "CreateConversation",
			Handler:    _ChatService_CreateConversation_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ChatService_GetMessages_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _ChatService_StreamMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat/chat.proto",
}

// Handler implementations
func _ChatService_GetConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetConversations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetConversations(ctx, req.(*GetConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/CreateConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateConversation(ctx, req.(*CreateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

type chatServiceStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).StreamMessages(m, &chatServiceStreamMessagesServer{stream})
}
